[project]
name = "searxngr"
version = "0.1.0"
description = "SearXNG from the terminal"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests>=2.32.3",
    "rich>=14.0.0",
    "xdg-base-dirs>=6.0.2",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://github.com/scross01/searxngr"
Issues = "https://github.com/scross01/searxngr/issues"

[project.scripts]
searxngr = "searxngr:main"
